CREATE TABLE ADDRESS (
  ADDRESS_ID NUMBER(19) AUTO_INCREMENT  PRIMARY KEY,
  VERSION NUMBER(19),
  ADD_ONE VARCHAR(250) NOT NULL,
  ADD_TWO VARCHAR(250),
  CITY VARCHAR(250),
  STATE VARCHAR(250) NOT NULL,
  COUNTRY VARCHAR(250)  NOT NULL,
  ZIP_CODE NUMBER(19) NOT NULL,
  CUSTOMER_ID NUMBER(19) NOT NULL
);

CREATE TABLE BILL (
    BILL_ID NUMBER(19) AUTO_INCREMENT  PRIMARY KEY,
    VERSION NUMBER(19),
  CUSTOMER_ID NUMBER(19) NOT NULL,
   TAX_RATE NUMBER(17,4) NOT NULL ,
  FINAL_PRICE NUMBER(17,4) NOT NULL ,
   BILL_DATE DATE NOT NULL
);

CREATE TABLE BILL_REF (
    BILL_ID NUMBER(19) NOT NULL,
 	 TOTAL_PRICE NUMBER(17,4) NOT NULL ,
   QUANTITY NUMBER(19) NOT NULL,
   PRODUCT_ID NUMBER(19)NOT NULL,
  VERSION NUMBER(19)
);
ALTER TABLE BILL_REF ADD CONSTRAINT BILL_REF_PK PRIMARY KEY(BILL_ID,PRODUCT_ID);

CREATE TABLE CUSTOMER (
  CUSTOMER_ID NUMBER(19) AUTO_INCREMENT  PRIMARY KEY,
  VERSION NUMBER(19),
  CUSTOMER_NAME VARCHAR(250)  NOT NULL,
  BILL_ID NUMBER(19)  NOT NULL
);

CREATE TABLE PRODUCT (
  PRODUCT_ID NUMBER (19)AUTO_INCREMENT  PRIMARY KEY,
  VERSION NUMBER(19),
  PRODUCT_NAME VARCHAR(250)  NOT NULL,
  COMPANY VARCHAR(250) ,
  RATE NUMBER(17,4) NOT NULL,
  IS_AVAILABLE BOOLEAN NOT NULL
);

CREATE TABLE USER(
 USER_ID NUMBER(19)AUTO_INCREMENT PRIMARY KEY,
 VERSION NUMBER(19),
 PASSWORD VARCHAR(250)NOT NULL,
 USER_NAME VARCHAR(250)NOT NULL,
 EMAIL VARCHAR(250)NOT NULL
 );
 
CREATE TABLE FEEDBACK(
 FEEDBACK_ID NUMBER(19)AUTO_INCREMENT PRIMARY KEY,
 FEEDBACK_MESSAGE VARCHAR(250),
 EMAIL VARCHAR(250)NOT NULL
 );